### ISSUE TITLE
Installer says "version 0.2.0"

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ObjectOrientedScripting#28]
I downloaded the current release(0.5.0) but the first page of the installer says it woulb be version 0.2.0

However the next page states the actual version but I thought that the version number at the front page might be a little "bug"

**Comment by X39** [comment]
gonna be fixed soon (ye ... it is a "bug" but oen that is bound to me being too lazy to update the version  ^^)

**Comment by X39** [comment]
closing this as it is a "kinda" bug
will be correct with next release again (or at least not THAT outdated anymore)
