### ISSUE TITLE
Obsolete files should get deleted

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ObjectOrientedScripting#29]
Assume the following example:
I write code where I define two functions. After translating I have 2 SQF-files corrseponding to these functions.
Now I decide that I only need one of the functions so I delete the second one in my code. After translating it again the SQF-file for the deleted function still exists in my output folder (the respective class-subFolder to be precice) which is some kind of confusing especially when you work on a project for a longer time so that you have multiple unused function-files accumulated in the output folder.

My suggestion would be to clean the output folder (As far as I see it it wouldn't take any extra translations if you delete these files beforehand) before translating the current OOS-file so that this folder contains relevant files only.

**Comment by X39** [comment]
would be possible easily
however, i am not sure if thats really the task of OOS

a simple batch script could solve that too
will add it as optional parameter to the wrapper thought

**Comment by Krzmbrzl** [comment]
I know that this is not complicated to do yourself but as OOS is generating these files anyway it could just as well take care about it :)

**Comment by X39** [comment]
Fixed in https://github.com/X39/ObjectOrientedScripting/commit/21e73be1c83712fd9dd0f49fc41ebcd86d37fb91
