### ISSUE TITLE
Include compiler batch in project 

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ObjectOrientedScripting#30]
As there is no GUI for OOS (yet) I think it would increase the work flow if the project generated by the Wrapper.exe included a batch file taking care about compiling the current project. 
Should be easy to implement as the compiler knows where it is located and the project location is given as an argument to the Wrapper.exe anyways.

**Comment by X39** [comment]
Nothing the compiler will take care about
batch scripts are for the user to be created (and whoever is capable of creating a modification or mission should be able to create a simple file with the extension .cmd and add the line for the compiling in there)

the UI will come with 0.6.0 patch
