### ISSUE TITLE
"extends" & "implements"

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ObjectOrientedScripting#31]
Would be nice to have the possibiliy to add a base class via the "extends" and an interface via the "implements" keyword. 
I know OOS is C-like and in C you just use the ':' operator but I think it would help people who are not used to C to understand what's going on as the access of namespaces/classes is done via the '::' operator so it can occur that there are a lot of colons in the class declaration which can be very confusing. 

Apart from that one would instantly know if the referenced field is a baseClass or just an interface.

**Comment by X39** [comment]
more keywords can lead to "problems" and confusion too

well ... its open for discussion

**Comment by flaver12** [comment]
I'm more from java and also PHP, the keywords would be nice, but I understand X39 argument of to many keywords, but I think this two keywords would be nice and in my opinion it would make the code more readable.

@X39 How many problems can this keywords make?

**Comment by X39** [comment]
> @X39 How many problems can this keywords make?

no problem at all (litterally just a new keyword i would have to add and depending on if we want to enforce the usage of implements for interfaces or if we just accept all lazy it requires some other coding too)

but i would not like to have both in the lang

**Comment by Krzmbrzl** [comment]
If you don't want both possibilities then I'd vote for the keywords instead if the colons :)

**Comment by X39** [comment]
its settled

extends will be added for base classes
implements for interfaces

**Comment by X39** [comment]
See release 0.5.3-ALPHA
