### ISSUE TITLE
Implement resource file

### ISSUE THREAD

**Issue by Krzmbrzl** [X39/ObjectOrientedScripting#39]
Would be nice to have the ability to add a resource path into the project.oosproj.

Like that:

```
<resource>resources.res</resource>
```

And foo.res would look like that:

```
ressource origin "PathToRessourceFile1" target "PathToOutputFile"
ressource origin "PathToRessourceFile2" target "PathToOutputFile"
```

The specified files would get copied to the given path during the compilation of the OOS code

the ressource file should allow the usage of the PreProcessor

**Comment by X39** [comment]
- Updated example and topic from folder oriented target to file oriented target
- Added note about allowing preprocessor usage

**Comment by Krzmbrzl** [comment]
Think I accidentally undid your changes...

**Comment by X39** [comment]
nope
fixed it after that again

**Comment by X39** [comment]
Done in v0.7.2
